### ISSUE TITLE
Add ligature for Khah and Yeh at the and of word

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [alif-type/amiri#148] opened 2018-03-27 16:32 UTC
Seen from the website, I found Khah and Yeh should become ligature for presented joining, compare with Ain-Yeh ligature.
![Look at red boxes](https://user-images.githubusercontent.com/10364351/37981127-5b3f7bc2-321f-11e8-9035-64871f07e08c.PNG)

**Comment by KrasnayaPloshchad** [comment] 2018-04-02 14:29
It seems to me that you have already implemented.
![Look!](https://i.imgur.com/j3kGDQu.png)
But it appears only in individual cases, not at the and of word.

**Comment by khaledhosny** [comment] 2019-12-07 04:50
Duplicate of #180

**Closed by khaledhosny** 2019-12-07 04:50 UTC
Labels: enhancement
